INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('María', 'Sanchez', 'maria@correo.es', '2019-11-11');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Jade', 'Doe', 'jane.doe@gmail.com', '2018-03-06');

INSERT INTO colecciones (nombre, num_totales, num_disponibles, create_at) VALUES('Los Vengadores', 130, 120, '2021-01-24');
INSERT INTO colecciones (nombre, num_totales, num_disponibles, create_at) VALUES('Capitán América', 130, 120, '2021-01-24');
INSERT INTO colecciones (nombre, num_totales, num_disponibles, create_at) VALUES('Thor', 12, 12, '2021-01-24');
INSERT INTO colecciones (nombre, num_totales, num_disponibles, create_at) VALUES('Spiderman', 130, 120, '2021-01-24');
INSERT INTO colecciones (nombre, num_totales, num_disponibles, create_at) VALUES('Daredevil', 130, 120, '2021-01-24');
INSERT INTO colecciones (nombre, num_totales, num_disponibles, create_at) VALUES('IronMan', 130, 120, '2021-01-24');
INSERT INTO colecciones (nombre, num_totales, num_disponibles, create_at) VALUES('Capitán América - Thor', 130, 120, '2021-01-24');
INSERT INTO colecciones (nombre, num_totales, num_disponibles, create_at) VALUES('Los Nuevos Vengadores', 130, 120, '2021-01-24');
INSERT INTO colecciones (nombre, num_totales, num_disponibles, create_at) VALUES('La Visión y la Bruja Escarlata', 130, 120, '2021-01-24');
INSERT INTO colecciones (nombre, num_totales, num_disponibles, create_at) VALUES('Secret Wars', 130, 120, '2021-01-24');
INSERT INTO colecciones (nombre, num_totales, num_disponibles, create_at) VALUES('Secret Wars II', 12, 12, '2021-01-24');
INSERT INTO colecciones (nombre, num_totales, num_disponibles, create_at) VALUES('Los 4 Fantásticos', 130, 120, '2021-01-24');
INSERT INTO colecciones (nombre, num_totales, num_disponibles, create_at) VALUES('Clásicos Marvel', 130, 120, '2021-01-24');
INSERT INTO colecciones (nombre, num_totales, num_disponibles, create_at) VALUES('Marvel Heroes', 130, 120, '2021-01-24');
INSERT INTO colecciones (nombre, num_totales, num_disponibles, create_at) VALUES('What if?', 130, 120, '2021-01-24');
INSERT INTO colecciones (nombre, num_totales, num_disponibles, create_at) VALUES('Hulk', 130, 120, '2021-01-24');